export interface DataType {
  'People Key': string;
  'Enterprise ID Name': string;
  'EID Code': string;
  'Conversation And Target Status': string;
  'Target Type': string;
  'CCI $ Actuals': string;
  'CCI % Actuals': string;
  'CI % Actuals': string;
  'CI % Target': string;
  'CI Target vs Actual Variance': string;
  'Confirmed CCI $ Actuals': string;
  'Confirmed Revenue Actuals': string;
  'Confirmed Sales Actuals': string;
  'Del CCI $ Plan': string;
  'Del CCI $ Plan/Target': string;
  'Del CCI % Plan': string;
  'Del CCI % Plan/Target': string;
  'Geographic Scope': string;
  'GILC Actuals': string;
  'Managed Won CCI % Target vs Actual Variance': string;
  'Managed Actuals As Of': string;
  'Managed Role': string;
  'Managed Won CCI % Actual': string;
  'Managed Won CCI % Target': string;
  'Master Client': string;
  'Practice': string;
  'Revenue Actuals': string;
  'Revenue Plan': string;
  'Revenue Plan/Target': string;
  'Role End Date': string;
  'Role Start Date': string;
  'Sales Actuals': string;
  'Sales Plan': string;
  'Sales Plan/Target': string;
  'Service/Group': string;
  'Targets Match To Financial Plan?': string;
  'FY Flag': string;
  'Managed Metric Model Type': string;
  'V and A Rating': string;
  'Confirmed Revenue Actuals(CC)': string;
  'Confirmed Sales Actuals(CC)': string;
  'Managed Chargeable FTE% Target': string;
  'Managed Chargeable FTE% Actuals': string;
  'Managed Chargeability Target': string;
  'Managed Chargeability Actuals': string;
}